//
//  TaxTermsData.swift
//  TaxAssist
//
//  This file is just a data list. To add a new dictionary entry,
//  copy the line format below and add it to the `taxTerms` array.
//  No other files need to change.
//
//  TaxTerm(term: "Your Word", definition: "Your simple explanation."),
//

import Foundation

struct TaxTerm: Identifiable {
    let id = UUID()
    let term: String
    let definition: String
}

let taxTerms: [TaxTerm] = [
    TaxTerm(term: "Adjusted Gross Income (AGI)", definition: "Your income after certain amounts are taken away."),
    TaxTerm(term: "Allowance", definition: "An older tax term used to help decide how much money was taken from your paycheck for taxes."),
    TaxTerm(term: "Audit", definition: "When the government checks your tax information to make sure it is correct."),
    TaxTerm(term: "Capital Gain", definition: "Money you make by selling something for more than you paid for it."),
    TaxTerm(term: "Capital Loss", definition: "Money you lose by selling something for less than you paid for it."),
    TaxTerm(term: "Claim", definition: "To include something on your taxes because it may affect how much you owe or get back."),
    TaxTerm(term: "Credit", definition: "An amount that directly lowers your tax bill."),
    TaxTerm(term: "Deduction", definition: "An amount that lowers the income the government uses to calculate your taxes."),
    TaxTerm(term: "Dependent", definition: "A person you financially support, such as a child."),
    TaxTerm(term: "Earned Income", definition: "Money you receive from working."),
    TaxTerm(term: "Estimated Tax", definition: "Tax payments you make during the year when taxes are not automatically taken from your income."),
    TaxTerm(term: "Exemption", definition: "An amount or situation that may exclude something from being taxed."),
    TaxTerm(term: "Federal Income Tax", definition: "Money paid to the U.S. government based on your income."),
    TaxTerm(term: "File / Filing", definition: "Sending your tax information to the government."),
    TaxTerm(term: "Filing Deadline", definition: "The last day you are normally expected to send in your taxes."),
    TaxTerm(term: "Filing Status", definition: "The household category you use when filing taxes."),
    TaxTerm(term: "Gross Income", definition: "The total money you made before anything is taken away."),
    TaxTerm(term: "Head of Household", definition: "A filing option for some unmarried people who pay most of the costs of a home for another person."),
    TaxTerm(term: "Income", definition: "Money you receive."),
    TaxTerm(term: "Income Tax", definition: "Tax based on the money you earn or receive."),
    TaxTerm(term: "IRS", definition: "The part of the U.S. government that handles federal taxes."),
    // NOTE: this definition was cut off in the original source ("A li..."). Placeholder below —
    // replace with your intended wording.
    TaxTerm(term: "Itemized Deductions", definition: "A list of specific expenses you can subtract from your income instead of taking the standard deduction."),
    TaxTerm(term: "Joint Return", definition: "A tax return filed together by a married couple."),
    TaxTerm(term: "Liability / Tax Liability", definition: "The amount of tax you are responsible for paying."),
    TaxTerm(term: "Married Filing Jointly", definition: "You and your spouse file one tax return together."),
    TaxTerm(term: "Married Filing Separately", definition: "You and your spouse file separate tax returns."),
    TaxTerm(term: "Nonrefundable Tax Credit", definition: "A tax credit that can lower your tax bill to $0 but usually will not give you extra money beyond that."),
    TaxTerm(term: "Refund", definition: "Money the government gives back when you paid more taxes than needed."),
    TaxTerm(term: "Refundable Tax Credit", definition: "A tax credit that may give you money back even if your tax bill reaches $0."),
    TaxTerm(term: "Return / Tax Return", definition: "The information and forms you send to the government about your income and taxes."),
    TaxTerm(term: "Self-Employment", definition: "Making money by working for yourself instead of as an employee."),
    TaxTerm(term: "Single", definition: "A filing status generally used by someone who is not married."),
    TaxTerm(term: "Standard Deduction", definition: "A set amount of income the government does not use when calculating your federal income tax."),
    TaxTerm(term: "State Income Tax", definition: "Tax paid to your state based on your income."),
    TaxTerm(term: "Taxable Income", definition: "The amount of your income the government uses to calculate your income tax."),
    TaxTerm(term: "Tax Bracket", definition: "A range of income taxed at a certain percentage."),
    TaxTerm(term: "Tax Credit", definition: "An amount that directly lowers the taxes you owe."),
    TaxTerm(term: "Tax Deduction", definition: "An amount that lowers the income used to calculate your taxes."),
    TaxTerm(term: "Tax Year", definition: "The year your tax information is about."),
    TaxTerm(term: "Withholding", definition: "Money your employer takes from your paycheck and sends toward your taxes."),
    TaxTerm(term: "Wages", definition: "Money you earn from working a job."),
    TaxTerm(term: "Salary", definition: "A set amount of money you are paid for your job."),
    TaxTerm(term: "Tips", definition: "Extra money customers give you for your work."),
    TaxTerm(term: "Pay Stub", definition: "A document showing how much you were paid and what money was taken out."),
    TaxTerm(term: "Payroll", definition: "The system your employer uses to pay workers."),
    TaxTerm(term: "Pre-Tax", definition: "Money taken out before some taxes are calculated."),
    TaxTerm(term: "Post-Tax", definition: "Money taken out after taxes are calculated."),
    TaxTerm(term: "Federal Withholding", definition: "Money taken from your paycheck for federal income taxes."),
    TaxTerm(term: "State Withholding", definition: "Money taken from your paycheck for state income taxes."),
    TaxTerm(term: "FICA", definition: "Federal Insurance Contributions Act, Payroll taxes that help fund Social Security and Medicare."),
    TaxTerm(term: "Social Security Tax", definition: "A payroll tax that helps fund Retirement, Widow/Widower benefits, and Disability."),
    TaxTerm(term: "Medicare Tax", definition: "A payroll tax that helps fund public Healthcare."),
    TaxTerm(term: "Net Pay", definition: "The money you actually receive after taxes and other amounts are taken out."),
    TaxTerm(term: "Gross Pay", definition: "Your pay before taxes and other amounts are taken out."),
    TaxTerm(term: "W-2", definition: "A form from your employer showing how much you were paid and how much tax was taken out."),
    TaxTerm(term: "W-4", definition: "A form you give your employer to help decide how much federal income tax to take from your paycheck."),
    TaxTerm(term: "1099", definition: "A type of form used to report certain money you received outside of regular employee wages."),
    TaxTerm(term: "1040", definition: "The main form most people use to file federal income taxes."),
    TaxTerm(term: "Form", definition: "An official document used to provide information."),
    TaxTerm(term: "Schedule ________", definition: "An extra tax form used to provide more details."),
    TaxTerm(term: "Box", definition: "A specific area on a tax form where information appears or is entered."),
    TaxTerm(term: "Taxpayer Identification Number (TIN)", definition: "A number the government uses to identify someone for tax purposes."),
    TaxTerm(term: "Social Security Number (SSN)", definition: "A personal identification number often used on tax forms."),
    TaxTerm(term: "Employer Identification Number (EIN)", definition: "A number used to identify a business for tax purposes."),
    TaxTerm(term: "Eligible Expense", definition: "A cost that meets the rules for a tax benefit."),
    TaxTerm(term: "Qualified Expense", definition: "A cost the tax rules say can be used for a specific tax benefit."),
    TaxTerm(term: "Business Expense", definition: "Money spent for your work or business."),
    TaxTerm(term: "Medical Expense", definition: "Money spent on certain healthcare costs."),
    TaxTerm(term: "Charitable Contribution", definition: "Money or certain items given to an eligible charity."),
    TaxTerm(term: "Mortgage Interest", definition: "Interest paid on a home loan."),
    TaxTerm(term: "Student Loan Interest", definition: "Interest paid on a home loan."),
    TaxTerm(term: "Contribution", definition: "Money you put into an account, plan, or organization."),
    TaxTerm(term: "Deductible", definition: "Allowed to lower the income used to calculate your taxes."),
    TaxTerm(term: "Interest Income", definition: "Money you earn from certain bank accounts or loans."),
    TaxTerm(term: "Dividend", definition: "Money a company may pay you for owning its stock."),
    TaxTerm(term: "Investment Income", definition: "Money earned from investments."),
    TaxTerm(term: "Asset", definition: "Something valuable that you own."),
    TaxTerm(term: "Cost Basis", definition: "Usually the amount you paid for an investment or property, adjusted in some situations."),
    TaxTerm(term: "Proceeds", definition: "Money you receive from selling something."),
    TaxTerm(term: "Realized Gain", definition: "Profit from something you actually sold above what you purchased it for."),
    TaxTerm(term: "Realized Loss", definition: "Loss from something you actually sold above what you purchased it for."),
    TaxTerm(term: "Short-Term Capital Gain", definition: "Profit from selling an investment you owned for one year or less."),
    TaxTerm(term: "Long-Term Capital Gain", definition: "Profit from selling an investment you owned for more than one year."),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    //TaxTerm(term: "", definition: ""),
    // Add new terms below this line:

]
